### ISSUE TITLE
Wrong argument of DeclareAttribute

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/sonata#1]
This has been previously reported at https://github.com/gap-system/gap/issues/2107 - please see the discussion there. We need to resolve this issue in order to include SONATA into GAP 4.10 distribution - it is currently disabled in the release candidates at it breaks regression tests there.

**Comment by fingolfin** [comment]
@PMayr note that this is fixed by https://github.com/gap-packages/sonata/pull/6 -- could you perhaps look into merging the three open PRs for this project? And then make a release?

Alternatively, we can merge them for you and perform the release. The offer also stands to add "The GAP team" as a (co-)maintainer
